### ISSUE TITLE
No running on windows

### ISSUE THREAD

**Issue by fighne** [dgvncsz0f/pydhcplib#6]
error message from running client example
Traceback (most recent call last):
  File "./dhcp_listen.py", line 21, in <module>
    from pydhcplib.dhcp_network import *
  File "C:\Python27\lib\site-packages\pydhcplib\dhcp_network.py", line 22, in <module>
    import IN
ImportError: No module named IN

**Comment by dgvncsz0f** [comment]
sorry about taking this long to reply. I somehow missed this message.

This is not going to work to windows without some work. In order to fully implement DHCP this library use a bit of C code to use raw socket.

When you are negotiating the IP address with the DHCP server you need to talk to a machine that has no IP yet. After you receive a message asking for an IP [which usually comes from a broadcasted message] you need to reply to the peer which at this point has no IP yet. When you reply the message to the peer you can (1) use broadcast [if I recall correctly the protocl allows this] or (2) more commonly use unicast. Replying to a machine that has no known IP address using unicast requires you to manipulate the IP headers directly, thus the use of C code to deal with raw sockets. This code is linux specific. 

Okay, now the error you are getting is not related to this particular issue but you would bump on it eventually.

I have no experience working with windows API but I'm willing to help if you still need this.

Again sorry taking this long to reply.
